### ISSUE TITLE
Root in jeffersonlab/clas12simulations:production

### ISSUE THREAD

**Issue by tylern4** [JeffersonLab/clas12-mcgen#1]
I was testing to add the 2pi_event_generator from https://github.com/JeffersonLab/Hybrid-Baryons to the list of generators but it seems that the docker image jeffersonlab/clas12simulations:production doesn't have libEG which is needed for TDatabasePDG.h which is used in the generator.

Does anyone know where the dockerfile for jeffersonlab/clas12simulations:production is located?  That would help to be able to fix this.

**Comment by maureeungaro** [comment]
I maintain the docker file in JeffersonLab/clas12container. Can you send me the steps to reproduce it, you can also use the interactive container here: 

https://clasweb.jlab.org/clas12/clas12SoftwarePage/html/index.html

**Comment by tylern4** [comment]
I've made a pull request to update the Dockerfile to have the required library and added the event generator over at https://github.com/JeffersonLab/clas12container.
